# Generated by Django 4.0.4 on 2022-05-31 14:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("contents", "0001_initial"),
        ("contents", "0002_channellanguage_alter_channel_language"),
        ("contents", "0003_author_contentgenre_content_description_and_more"),
        ("contents", "0004_channel_picture"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChannelLanguage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=32, unique=True)),
                ("code", models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contents.channellanguage",
                    ),
                ),
                ("picture", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("surname", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ContentGenre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.IntegerField()),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contents.channel",
                    ),
                ),
                ("description", models.CharField(max_length=1024)),
                ("authors", models.ManyToManyField(to="contents.author")),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contents.contentgenre",
                    ),
                ),
            ],
        ),
    ]
