# Generated by Django 4.0.4 on 2022-05-31 11:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelLanguage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=32, unique=True)),
                ("code", models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="channel",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contents.channellanguage",
            ),
        ),
    ]
