# Generated by Django 4.0.4 on 2022-05-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_content_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="contents.channel",
            ),
        ),
        migrations.AlterField(
            model_name="contentgenre",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
