openapi: 3.0.3

info:
  title: Immfly content API
  version: "0.1"

servers:
  - url: http://localhost:8000
  - url: http://localhost:4010

paths:
  /api/channels/:
    get:
      operationId: listChannels
      description: API endpoint that allows channels listing.
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Channel'
          description: ""
      tags:
        - contents
  /api/channels/{id}/:
    get:
      operationId: retrieveChannel
      description: API endpoint that allows channel retrieval.
      parameters:
        - name: id
          in: path
          required: true
          description: A UUID string identifying this channel.
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
          description: ""
      tags:
        - contents
  /api/contents/{id}/:
    get:
      operationId: retrieveContent
      description: API endpoint that allows content retrieval.
      parameters:
        - name: id
          in: path
          required: true
          description: A UUID string identifying this content.
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ""
      tags:
        - contents

components:
  schemas:
    Channel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        language:
          type: string
        picture:
          type: string
          format: uri
        rating:
          type: integer
          minimum: 1
          maximum: 10
        contents:
          type: array
          items:
            type: string
            format: uri
        subchannels:
          type: array
          items:
            type: string
            format: uri
    Content:
      type: object
      properties:
        id:
          type: string
          format: uuid
        files:
          type: array
          items:
            type: string
            format: uri
        description:
          type: string
        authors:
          type: array
          items:
            type: string
        genre:
          type: string
        rating:
          type: integer
          minimum: 1
          maximum: 10
