openapi: 3.0.3

info:
  title: Immfly content API
  version: "0.1"

servers:
  - url: http://localhost:8000
  - url: http://localhost:4010

paths:
  /api/channels/:
    get:
      operationId: listChannels
      description: API endpoint that allows channels listing.
      parameters:
        - name: page
          required: false
          in: query
          description: A page number within the paginated result set.
          schema:
            type: integer
        - name: search
          required: false
          in: query
          description: A search term.
          schema:
            type: string
        - name: ordering
          required: false
          in: query
          description: Which field to use when ordering the results.
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/channels/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/channels/?page=2
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Channel"
          description: ""
      tags:
        - channels
  /api/channels/{id}/:
    get:
      operationId: retrieveChannel
      description: API endpoint that allows channel retrieval.
      parameters:
        - name: id
          in: path
          required: true
          description: A UUID string identifying this channel.
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Channel"
          description: ""
      tags:
        - channels

components:
  schemas:
    Channel:
      oneOf:
        - $ref: "#/components/schemas/ChannelWithContents"
        - $ref: "#/components/schemas/ChannelWithSubchannels"
    ChannelWithContents:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        language:
          type: string
        picture:
          type: string
          format: uri
        contents:
          type: array
          items:
            $ref: "#/components/schemas/Content"
    ChannelWithSubchannels:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        language:
          type: string
        picture:
          type: string
          format: uri
        subchannels:
          type: array
          items:
            $ref: "#/components/schemas/Channel"
    Content:
      type: object
      properties:
        id:
          type: string
          format: uuid
        files:
          type: array
          items:
            type: string
            format: uri
        metadata:
          $ref: "#/components/schemas/Metadata"
        rating:
          type: integer
    Metadata:
      type: object
      properties:
        description:
          type: string
        authors:
          type: array
          items:
            type: string
        genre:
          type: string
