name: CICD

on:
  pull_request:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.3
          cache: 'pipenv'
      - run: pipenv install --dev --ignore-pipfile
      - run: pipenv run ./manage.py test
        env:
          DJANGO_SETTINGS_MODULE: immfly.settings.test
          DB_HOST: localhost
          DB_NAME: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
